### ISSUE TITLE
Question: Limit in ROI?

### ISSUE THREAD

**Issue by beniroquai** [kasasxav/ImSwitch#100]
Hey, me again. I just implemented the ROI functoin in the Daheng camera and I cannot set any valuehigher than 256 or 100 for width/height in the ImSwitch ROI Manager. Is this intended? I could not find any code that would descrbe that. Perhaps I missed some setting in the Json?

**Comment by kasasxav** [comment]
Isn't it the limit you have in your `setROI` that it does max between 256 and the number you input?

**Comment by kasasxav** [comment]
gxipycamera.py  line 150

**Comment by kasasxav** [comment]
In the hamamatsu we can put up to 2048 (fullChip), so I think it will be somewhere in your manager. It could also be the` fullShape `parameter being too small.

**Comment by beniroquai** [comment]
Damn! You are so smart! 
Indeed, I have read the sensor width/height from the cropped camera sensor. After each restart, it's a different value and limiting the ROI. Perfect! Thanks :)
