### ISSUE TITLE
ImSwitch Config same name as ImSwitch base

### ISSUE THREAD

**Issue by beniroquai** [kasasxav/ImSwitch#111]
Hey, 
one weird "error" was found today when we installed Imswitch on another computer (was soo much fun ;-)..
When people "accidentally" download the folder to Documents, the ImSwitch config folder is again created recursively. I was wondering if it's plausible to rename it to something like `ImSwitchConfig` or alike?

**Comment by kasasxav** [comment]
#5a5a9b47cc1bae412554745adec97f4d2d353bcb this will do

**Comment by kasasxav** [comment]
https://github.com/kasasxav/ImSwitch/commit/5a5a9b47cc1bae412554745adec97f4d2d353bcb this will do :)

**Comment by beniroquai** [comment]
Thanks! Awesome! :)
