### ISSUE TITLE
Saving options

### ISSUE THREAD

**Issue by AZehrer** [kasasxav/ImSwitch#116]
Hi, i am using imswitch for multi channel imaging and was wondering if there was a way to save the images with a suffix corresponding to the channel it was acquired in.
Also, would it be possible to save images of a time series in the same hdf5 file? So for example if an image was acquired every 10min ( api.imcontrol.snapImage() ) for 10hrs with a python script iterating over time, can i save all the 60 images in the same hdf5 file? Right now i only managed to save each image as a single hdf5 file.
Thanks for your help,
Best, Ando

**Comment by kasasxav** [comment]
Hi Ando,
Now how it is done is that if you use the recording manager (for example rec until stop), it will save everything in an hdf5 files with all the metadata (including the channel) and each channel will be a different dataset inside the same hdf5 file. The rec function will get all the new frames from the camera (using the function grabChunk, which camera are you using by the way?).

**Comment by kasasxav** [comment]
If you could use the same[ rec until stop function](https://github.com/kasasxav/ImSwitch/blob/master/imswitch/_data/user_defaults/scripts/example_record.py) then you would have everything easier, but otherwise we can try to do it for snap Image too
