### ISSUE TITLE
cv2 loaded in RecordingManager but not installed with pip package ImSwitch

### ISSUE THREAD

**Issue by jonatanalvelid** [kasasxav/ImSwitch#127]
Hello,

Small but breaking issue: due to recent changes in RecordingManager cv2 is now a requirement, but it is currently not installed with pip install imswitch. 
Solution: pip package should be updated with the new requirements.

**Comment by kasasxav** [comment]
Hi,
The dependencies are in setup.cfg, but you have to go into ImSwith folder and run "pip install .", pip install imswitch will install the PyPi release which is older!
