### ISSUE TITLE
Pyro5, useq, NanoImagingPack new requirements - not installed with pip install ImSwitch

### ISSUE THREAD

**Issue by jonatanalvelid** [kasasxav/ImSwitch#128]
Hello,

Small but breaking issues: due to recent changes and additions Pyro5 (pip Pyro5), useq (pip useq-schema), NanoImagingPack (git+https://gitlab.com/bionanoimaging/nanoimagingpack) are all now requirements, but they are currently not installed with pip install imswitch.
Solution: pip package ImSwitch should be updated with the new requirements.

**Comment by kasasxav** [comment]
Same as #127, NanoImagingPack is commented but we are trying to find a way to install it without the gitlab website.
