### ISSUE TITLE
ImSwitch requirement pyqtgraph new version doesnt have function qtime

### ISSUE THREAD

**Issue by ranranking** [kasasxav/ImSwitch#144]
**Bug description**

I tried to install imswitch in a new pc, and it shows up the dependicy with `pyqtgraph == 0.13` few error. It might be the newest doesnt have `pyqtgraph.ptime`, since `python >= 3.7` doesnt need it.

**Environment**
 - OS: Windows 10
 - ImSwitch version: 1.2.1
 - How you downloaded ImSwitch: [either "pip" or "standalone bundle"]

**Comment by kasasxav** [comment]
Hi @ranranking , I thought I fixed it with #141 (https://github.com/kasasxav/ImSwitch/issues/141). Do you have that update in your version?

**Comment by kasasxav** [comment]
Also could you copy here your error message?

Thanks for reaching out!

**Comment by ranranking** [comment]
On me it written with pyqtgraph has no attribute ptime. I also used the same methods as Jacopo reinstalled 0.12.1 and it works

发送自 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Xavier ***@***.***>
发送时间: Wednesday, December 21, 2022 8:04:27 PM
收件人: kasasxav/ImSwitch ***@***.***>
抄送: ranranking ***@***.***>; Mention ***@***.***>
主题: Re: [kasasxav/ImSwitch] ImSwitch requirement pyqtgraph new version doesnt have function qtime (Issue #144)


Also could you copy here your error message?

Thanks for reaching out!

―

**Comment by kasasxav** [comment]
great !! all good then?
