### ISSUE TITLE
Fail to start the ScanWidget

### ISSUE THREAD

**Issue by hzarei4** [kasasxav/ImSwitch#184]
Hello,

I am trying to trigger the Hamamatsu camera using the NIDAQ card. I do it using the Scan widget like the MONALISA example config file. But when I start the ImSwitch, it gives this error:

`AttributeError: module 'imswitch.imcontrol.view.widgets' has no attribute 'ScanWidgetNone'`

Could you please help me with what is not correct here?

The config file that I am using is this:

```
{
    "detectors": {
        "Green": {
            "analogChannel": null,
            "digitalLine": "COM9",
            "managerName": "HamamatsuManager",
            "managerProperties": {
                "cameraListIndex": 0,
                "hamamatsu": {
                    "trigger_global_exposure": 5,
                    "trigger_active": 2,
                    "trigger_polarity": 2,
                    "exposure_time": 0.01,
                    "trigger_source": 1,
                }
            },
            "forAcquisition": true
        },
    },
    "scan": {
        "scanDesigner": "BetaScanDesigner",
        "scanDesignerParams": {
            "return_time": 0.01
        },
        "TTLCycleDesigner": "BetaTTLCycleDesigner",
        "TTLCycleDesignerParams": {},
        "sampleRate": 100000
    },
    "nidaq": {
        "timerCounterChannel": null,
        "startTrigger": false
    },
    "availableWidgets": [
        "Settings",
        "View",
        "Recording",
        "Image",
        "Scan"
    ]
}
```

**Comment by beniroquai** [comment]
Hey @hzarei4, thanks for reaching out. May I ask you which version of ImSwitch you installed?

**Comment by hzarei4** [comment]
Hi @beniroquai, 
I installed the latest version of the ImSwitch, version 2.0.0.

**Comment by beniroquai** [comment]
This sounds like the uc2 version, right?
How did you install it?
You can remove this error by removing any scan related settings in the json
file

**Comment by hzarei4** [comment]
Dear @beniroquai 

> This sounds like the uc2 version, right? How did you install it? 

I don't think so. I have cloned and installed it from the source code on this link: 
[https://github.com/ImSwitch/ImSwitch](https://github.com/ImSwitch/ImSwitch)

> You can remove this error by removing any scan related settings in the json file

But I want the signal generation (Scan) widget of the ImSwitch. Because I want to generate a signal for the components in my setup. Do I have to design my own application's scan widget?

**Comment by jacopoabramo** [comment]
Hi @hzarei4 can you please post the entire stack trace so that I can retrace all the steps of where the error is generated?

**Comment by hzarei4** [comment]
Hi Jacopo,

The error trace in command line is as follows:

´´´
2023-08-09 14:04:22 ERROR [main] Failed to initialize module imcontrol
2023-08-09 14:04:22 ERROR [main] Traceback (most recent call last):
  File "C:\Users\admin\Desktop\ImSwitch\imswitch\__main__.py", line 51, in
main
    view, controller = modulePkg.getMainViewAndController(
  File "C:\Users\admin\Desktop\ImSwitch\imswitch\imcontrol\__init__.py",
line 52, in getMainViewAndController
    view = ImConMainView(options, setupInfo)
  File
"C:\Users\admin\Desktop\ImSwitch\imswitch\imcontrol\view\ImConMainView.py",
line 100, in __init__
    rightDocks = self._addDocks(
  File
"C:\Users\admin\Desktop\ImSwitch\imswitch\imcontrol\view\ImConMainView.py",
line 157, in _addDocks
    getattr(widgets,
f'{widgetKey}Widget{self.viewSetupInfo.scan.scanWidgetType}')
AttributeError: module 'imswitch.imcontrol.view.widgets' has no attribute
'ScanWidgetNone'
´´´

And in the ImSwitch application:

´´´´

AttributeError: module 'imswitch.imcontrol.view.widgets' has no attribute
'ScanWidgetNone'
´´´

**Comment by jacopoabramo** [comment]
Try adding in the "scan" dictionary the following key-item:

```
"scanWidgetType" : "MoNaLISA"
```

This is a necessary key defined in the `ScanInfo` dataclass in the `SetupInfo.py` module

**Comment by hzarei4** [comment]
Fixed!

I think I figured it out how to design the scan widget using the signal generators.

Thanks a lot!
