### ISSUE TITLE
Improve handling of the multidata reconstructed images

### ISSUE THREAD

**Issue by fpenna** [kasasxav/ImSwitch#34]
In the “Image reconstruction” is it possible to save the reconstructed images of a multidata in one only file, for example accessible by moving one of the slider (i.e. the Dataset)? In other words to have as an output of a "reconstruct multidata" a stack instead of a group of separate images.  
In alternative, it would be very useful to save a group of reconstructed file all at the same time. The problem right now is that each file has to be save separately, aspect that become a bottleneck if you are dealing with several time-lapses of more than 10 frame each.

**Comment by kasasxav** [comment]
When you do a 3d stack using only the scan module, it reconstructs everything in the same file. Can you check if the slider works in that case?
Otherwise, this is more an issue of the time-lapse implementation, so we should think about it properly.

**Comment by fpenna** [comment]
I never used the 3D stack but I can give it a try.
Right now it does reconstruct all the images of a timelapse (even if they have different length) but the main difficulty here is that if you have a lot of reconstructed data to save you have to do it one-by-one, thing that become difficult  when you have 100 images. Also just a way to select multiple images on the list of the reconstructed and save them all together will be extremely helpful.
