### ISSUE TITLE
distribution

### ISSUE THREAD

**Issue by untzag** [kasasxav/ImSwitch#38]
Most scientific Python users prefer to install their non-development software via PyPI or conda-forge. If ImSwitch intends to grow to support non-developer end-users it should be available from these package managers. I'm happy to personally provide guidance on how to set up a pipeline for releasing, if desired.

#40 must be resolved before ImSwitch can be distributed

(I am a JOSS reviewer but this issue is NOT blocking to JOSS publication in my opinion)

**Comment by stafak** [comment]
Thanks for your feedback! We have now published ImSwitch on PyPI (handled through a simple pipeline), and for Windows users we are additionally publishing standalone bundles on the releases page on GitHub.

**Comment by untzag** [comment]
Thanks @stafak, I'm personally satisfied by what you've done. Lovely to know that ImSwitch is just a `pip install` away now :smile:
