### ISSUE TITLE
Add functionality to save multiple scans in the same hdf5-file

### ISSUE THREAD

**Issue by kasasxav** [kasasxav/ImSwitch#53]

**Comment by kasasxav** [comment]
This applies mostly only to Time-laps scan. We can include a setting there.

**Comment by kasasxav** [comment]
How to do this:

The different situations where we want to choose between saving the recordings in one or more files so far are 1) multi-detector recording and 2) timelapse

In 1) we can create a checkbox and change line 108 of RecordingManager so it only creates one file with different datasets.

For 2), we can add another checkbox and change line 108 as well, so whenever the user wants to record timelapse in the same file we open the same filename and create a different dataset.

**Comment by stafak** [comment]
Blocking: #70, #71
