### ISSUE TITLE
"nicaiu" module not found on lunch

### ISSUE THREAD

**Issue by jacopoabramo** [kasasxav/ImSwitch#79]
**Bug description**
When trying to open ImSwitch from the command line, the following error shows on the GUI:

![imswitch_failed_launch](https://user-images.githubusercontent.com/20145526/135995558-e78ba3a7-295d-4522-aecd-203f39f637f1.PNG)

I'm also attaching the following launch log:

> 2021-10-05 11:16:30 DEBUG [ImConMainController] Initializing
> 2021-10-05 11:16:30 WARNING [RS232Manager -> aaaotf] Initializing mock RS232 port
> 2021-10-05 11:16:30 WARNING [RS232Manager -> pczpiezo] Initializing mock RS232 port
> 2021-10-05 11:16:30 DEBUG [APDManager -> APDred] sigScanInitiate is connected
> 2021-10-05 11:16:30 DEBUG [APDManager -> APDgreen] sigScanInitiate is connected
> 2021-10-05 11:16:30 WARNING [TISManager -> WidefieldCamera] Failed to initialize TIS camera 1, loading mocker
> 2021-10-05 11:16:30 INFO [TISManager -> WidefieldCamera] Initialized camera, model: mock
> 2021-10-05 11:16:30 DEBUG [TISManager -> WidefieldCamera] stoplive
> 2021-10-05 11:16:30 WARNING [TISManager -> FocusLockCamera] Failed to initialize TIS camera 0, loading mocker
> 2021-10-05 11:16:30 INFO [TISManager -> FocusLockCamera] Initialized camera, model: mock
> 2021-10-05 11:16:30 DEBUG [TISManager -> FocusLockCamera] stoplive
> 2021-10-05 11:16:30 DEBUG [MockRS232Driver -> ASRL4::INSTR] Sending the following to ASRL4::INSTR: L0I1O1
> 2021-10-05 11:16:30 DEBUG [MockRS232Driver -> ASRL4::INSTR] Sending the following to ASRL4::INSTR: L1I1
> 2021-10-05 11:16:30 DEBUG [MockRS232Driver -> ASRL4::INSTR] Sending the following to ASRL4::INSTR: L0I1O1
> 2021-10-05 11:16:30 DEBUG [MockRS232Driver -> ASRL4::INSTR] Sending the following to ASRL4::INSTR: L2I1
> 2021-10-05 11:16:30 ERROR [SLMManager] No BMP files found in correction patterns directory, cannot initialize correction mask.
> 2021-10-05 11:16:30 DEBUG [TISManager -> FocusLockCamera] stoplive
> 2021-10-05 11:16:30 DEBUG [TISManager -> FocusLockCamera] startlive
> 2021-10-05 11:16:30 DEBUG [MockRS232Driver -> ASRL4::INSTR] Sending the following to ASRL4::INSTR: L1P0
> 2021-10-05 11:16:30 DEBUG [MockRS232Driver -> ASRL4::INSTR] Sending the following to ASRL4::INSTR: L2P0
> 2021-10-05 11:16:30 DEBUG [ImConMainController] Shutting down
> 2021-10-05 11:16:30 ERROR [main] Failed to initialize module imcontrol
> 2021-10-05 11:16:30 ERROR [main] Traceback (most recent call last):
>   File "C:\Users\jacop\AppData\Local\Programs\Python\Python39\lib\site-packages\imswitch\__main__.py", line 50, in main
>     view, controller = modulePkg.getMainViewAndController(
>   File "C:\Users\jacop\AppData\Local\Programs\Python\Python39\lib\site-packages\imswitch\imcontrol\__init__.py", line 55, in getMainViewAndController
>     raise e
>   File "C:\Users\jacop\AppData\Local\Programs\Python\Python39\lib\site-packages\imswitch\imcontrol\__init__.py", line 52, in getMainViewAndController
>     controller = ImConMainController(options, setupInfo, view, moduleCommChannel)
>   File "C:\Users\jacop\AppData\Local\Programs\Python\Python39\lib\site-packages\imswitch\imcontrol\controller\ImConMainController.py", line 52, in __init__
>     self.controllers[widgetKey] = self.__factory.createController(
>   File "C:\Users\jacop\AppData\Local\Programs\Python\Python39\lib\site-packages\imswitch\imcommon\controller\basecontrollers.py", line 46, in createController
>     controller = controllerClass(*self.__args, *args,
>   File "C:\Users\jacop\AppData\Local\Programs\Python\Python39\lib\site-packages\imswitch\imcontrol\controller\controllers\LaserController.py", line 26, in __init__
>     self.valueChanged(lName, lManager.valueRangeMin)
>   File "C:\Users\jacop\AppData\Local\Programs\Python\Python39\lib\site-packages\imswitch\imcontrol\controller\controllers\LaserController.py", line 66, in valueChanged
>     self._master.lasersManager[laserName].setValue(magnitude)
>   File "C:\Users\jacop\AppData\Local\Programs\Python\Python39\lib\site-packages\imswitch\imcontrol\model\managers\lasers\NidaqLaserManager.py", line 22, in setValue
>     self._nidaqManager.setAnalog(
>   File "C:\Users\jacop\AppData\Local\Programs\Python\Python39\lib\site-packages\imswitch\imcontrol\model\managers\NidaqManager.py", line 232, in setAnalog
>     aotask = self.__createChanAOTask('setAnalogTask',
>   File "C:\Users\jacop\AppData\Local\Programs\Python\Python39\lib\site-packages\imswitch\imcontrol\model\managers\NidaqManager.py", line 51, in __createChanAOTask
>     aotask = nidaqmx.Task(name)
>   File "C:\Users\jacop\AppData\Local\Programs\Python\Python39\lib\site-packages\nidaqmx\task.py", line 84, in __init__
>     self._handle = lib_importer.task_handle(0)
>   File "C:\Users\jacop\AppData\Local\Programs\Python\Python39\lib\site-packages\nidaqmx\_lib.py", line 178, in task_handle
>     self._parse_typedefs()
>   File "C:\Users\jacop\AppData\Local\Programs\Python\Python39\lib\site-packages\nidaqmx\_lib.py", line 241, in _parse_typedefs
>     version = system.driver_version
>   File "C:\Users\jacop\AppData\Local\Programs\Python\Python39\lib\site-packages\nidaqmx\system\system.py", line 73, in driver_version
>     return DriverVersion(self._major_version, self._minor_version,
>   File "C:\Users\jacop\AppData\Local\Programs\Python\Python39\lib\site-packages\nidaqmx\system\system.py", line 108, in _major_version
>     cfunc = lib_importer.windll.DAQmxGetSysNIDAQMajorVersion
>   File "C:\Users\jacop\AppData\Local\Programs\Python\Python39\lib\site-packages\nidaqmx\_lib.py", line 166, in windll
>     self._import_lib()
>   File "C:\Users\jacop\AppData\Local\Programs\Python\Python39\lib\site-packages\nidaqmx\_lib.py", line 209, in _import_lib
>     windll = ctypes.windll.LoadLibrary(lib_name)
>   File "C:\Users\jacop\AppData\Local\Programs\Python\Python39\lib\ctypes\__init__.py", line 452, in LoadLibrary
>     return self._dlltype(name)
>   File "C:\Users\jacop\AppData\Local\Programs\Python\Python39\lib\ctypes\__init__.py", line 374, in __init__
>     self._handle = _dlopen(self._name, mode)
> FileNotFoundError: Could not find module 'nicaiu' (or one of its dependencies). Try using the full path with constructor syntax.
> 
> Exception ignored in: <function Task.__del__ at 0x000002A74D9A3A60>
> Traceback (most recent call last):
>   File "C:\Users\jacop\AppData\Local\Programs\Python\Python39\lib\site-packages\nidaqmx\task.py", line 101, in __del__
>     if self._handle is not None:
> AttributeError: 'Task' object has no attribute '_handle'

**How to reproduce**
1. download ImSwitch via `pip install imswitch`
2. call `imswitch` from command prompt

**Expected behavior**
Correct launch of ImSwitch.

**Environment**
 - OS: Windows 10, x64 arch.
 - ImSwitch version 1.2.1
 - Python version 3.9.7
 -  pip

**Additional context**
None so far.

**Comment by jethro33** [comment]
Adding a comment with some extra information: a while ago I installed ImSwitch with the same procedure (via pip) on a laptop which had installed, for separate reasons, the NI device manager software. Don't know if that information is useful somewhat, I'll try to elaborate further in case you have other questions.

**Comment by kasasxav** [comment]
ImSwitch should work without the nidaq though, but maybe you have it installed but are missing some driver?
